# Generated by Django 3.0.5 on 2020-05-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api1_forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name2', models.CharField(default='test', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
